# Generated by Django 4.1 on 2023-04-04 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0004_alter_categorised_list_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorised_list',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='votingapp.category'),
        ),
    ]
