# Generated by Django 4.1 on 2023-04-04 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0005_alter_categorised_list_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='categories',
        ),
    ]
