# Generated by Django 4.1 on 2023-04-05 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0006_remove_group_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestions',
            name='likes',
        ),
        migrations.AddField(
            model_name='suggestions',
            name='voters',
            field=models.ManyToManyField(related_name='voters', to=settings.AUTH_USER_MODEL),
        ),
    ]
